Fix pypi build
All-Hands-AI/OpenHands pull request #3548
Opened 2024-08-22 20:29 UTC by tofarr

This is intended to address https://github.com/All-Hands-AI/OpenHands/issues/3527

As pointed out by a user, our build on pypi does not include agenthub. This is intended to address that.

2024-08-22 22:18 UTC, neubig requested changes
Looks good to me! But we should probably not cut a release just yet. When we do, probably bumping to 0.9.0 would be good.

2024-08-22 22:18 UTC, neubig commented on pyproject.toml
> +version = "0.8.4"
We probably shouldn't cut a new release until we're pretty sure that we don't have any regressions in agent quality. I think @mamoodi is taking a final look now.

2024-08-22 22:32 UTC, tobitege commented
@tofarr When you change the version number, please also apply that to the 2 `/frontend/package*.json` files :)

2024-08-23 15:38 UTC, neubig commented
Hey @tofarr , we're going to have to change the name of the package to openhands-ai to match the pypi distribution. I changed that in a commit, but that's breaking other things e.g. in the runtime tests, which will have to be fixed.

2024-08-23 16:46 UTC, neubig commented
Just for reference, I tested this out locally and it seems to be working if I add:
```
openhands-ai = { git = "https://github.com/All-Hands-AI/openhands.git", rev = "fix-pypi-package" }
```

to `pyprojects.toml`. So once tests are working I think it's good to go!

2024-08-24 01:05 UTC, neubig approved these changes
LGTM now that 0.9.0 is released, lets see if tests pass.

2024-08-26 07:31 UTC, merged