fix(frontend): Error when API key is not entered is not clear #4236
All-Hands-AI/OpenHands pull request #4429
Opened 2024-10-16 14:23 UTC by Yashwanth-Chandrakumar

Give a summary of what the PR does, explaining any non-trivial design decisions

Added a modal for prompting the user to input an API Key in settings during startup and in session.

Link of any specific issues this addresses

https://github.com/All-Hands-AI/OpenHands/issues/4236

2024-10-16 14:30 UTC, Yashwanth-Chandrakumar commented
@amanape is this good

2024-10-17 13:32 UTC, Yashwanth-Chandrakumar commented
@amanape i have solved the issue but why isnt it merged

2024-10-17 14:40 UTC, amanape commented
I will give a proper review soon, sorry for the delay! In the meantime, I see that there are some linting issues on the frontend. Could you take care of it to pass the GitHub CI?

2024-10-17 14:42 UTC, Yashwanth-Chandrakumar commented
Yes i think the prettier in my code editor is causing the problem will solve it. @amanape

2024-10-18 04:13 UTC, Yashwanth-Chandrakumar commented
@amanape solved the lint issues perfect to merge

2024-10-18 04:32 UTC, amanape reviewed
The functionality does not work when pressing "Save". The flow should look something like this:

- User presses "Save"
- If there is no API key, show modal
- Otherwise, send the save settings action request (it currently only does this)

We are using Remix to handle form actions. Instead of keeping `LLM_API_KEY` changes in the `hasEnteredKey` state, we can access this setting from the `formRef`:

```ts
const formData = new FormData(formRef.current); // assuming formRef.current is not undefined
const apiKey = formData.get("api-key");
```

You should prefer using Remix / React Router (latest version) API to handle form data and navigation states. I recommend reading their documentation for more information!

2024-10-18 04:32 UTC, amanape commented on frontend/src/components/form/settings-form.tsx
> +    console.log("Close clicked, hasEnteredKey:", hasEnteredKey);
Remove the `console.log`

2024-10-18 04:32 UTC, amanape commented on frontend/src/components/form/settings-form.tsx
> +      console.log("Showing warning modal");
Remove the `console.log`

2024-10-18 04:32 UTC, amanape commented on frontend/src/components/form/settings-form.tsx
> +      console.log("Closing settings");
Remove the `console.log`

2024-10-18 04:32 UTC, amanape commented on frontend/src/components/form/settings-form.tsx
> +    console.log("API key changed, new value:", newValue);
Remove the `console.log`

2024-10-18 06:03 UTC, Yashwanth-Chandrakumar commented
@amanape ok i will implement the changes and come back

2024-10-18 13:11 UTC, Yashwanth-Chandrakumar commented
Hi @amanape corrected the flow and other eslint issues (removed all the console log statements).

2024-10-20 14:26 UTC, Yashwanth-Chandrakumar commented
@amanape all checks are done can we merge it

2024-10-21 06:33 UTC, amanape requested changes
There seems to be just one bug:

1. Set API key and save
2. Open settings again
3. Clear API key input and press "Save"
4. Confirm warning modal

In this case, the API key is not actually removed, and still there.

2024-10-21 09:41 UTC, Yashwanth-Chandrakumar commented
@amanape solved the bug, ready to merge

2024-10-22 18:23 UTC, amanape approved these changes
Thanks for the changes! Bonus points for handling the zIndex, too.

2024-10-22 18:23 UTC, merged