Fix Issue #3325
All-Hands-AI/OpenHands pull request #5004
Opened 2024-11-14 19:43 UTC by Mr-Imperium

Added a configuration options md file to openhands/docs. Added appropriately to sidebars.ts. Fixes #3325

**End-user friendly description of the problem this fixes or functionality that this introduces**

- [X] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
Resolves #3325

2024-11-14 20:30 UTC, enyst requested changes
Thank you for working on this, @Mr-Imperium ! This issue might be tricky, because of just how many configuration options there are.

- I would mostly suggest to take a look at `config.toml.template` file, [here](https://github.com/All-Hands-AI/OpenHands/blob/main/config.template.toml), we have usually tried to keep it up to date, as an example that users can modify as they need
- I'm afraid the LLM you used hallucinated some default values 😅. For example, AWS defaults are all None, there's no 'us-west' anywhere. The LLM specific options, including AWS options, are [here](https://github.com/All-Hands-AI/OpenHands/blob/01cacf7c331b29b915c970561aeffd41dff55def/openhands/core/config/llm_config.py#L16), the same for others, like prompt caching is by default `True`.
- for the record, the [config module](https://github.com/All-Hands-AI/OpenHands/tree/main/openhands/core/config) where all *config.py files are, is the implementation of all these options

2024-11-17 16:48 UTC, Monkub81 approved these changes

2024-11-17 16:49 UTC, Monkub81 approved these changes

2024-11-21 03:57 UTC, enyst commented
@Mr-Imperium Sorry, I think there are two files now? Can you please take a look

2024-11-21 13:58 UTC, Mr-Imperium commented
> @Mr-Imperium Sorry, I think there are two files now? Can you please take a look

Updated, please review them.

2024-11-25 12:11 UTC, enyst commented on docs/modules/usage/configuration-options.md
> +  - Description: Enable saving and restoring the session when run from CLI
Just a small thing here, this does not exist anymore. It was removed sometime last month or so

2024-11-25 12:14 UTC, enyst commented on docs/modules/usage/configuration-options.md
> +  - Default: `""`
```suggestion
  - Default: `uuid.uuid4().hex`
```

2024-11-25 12:15 UTC, enyst commented on docs/modules/usage/configuration-options.md
> +  - Description: JWT secret for authentication
```suggestion
  - Description: JWT secret for authentication. Please set it to your own value.
```

2024-11-25 12:17 UTC, enyst commented on docs/modules/usage/configuration-options.md
> +  - Description: Path to rewrite the workspace mount path to
```suggestion
  - Description: Path to rewrite the workspace mount path to. You can usually ignore this, it refers to special cases of running inside another container.
```

2024-11-25 12:19 UTC, enyst commented on docs/modules/usage/configuration-options.md
> +  - Description: Path to store trajectories (can be a folder or a file)
```suggestion
  - Description: Path to store trajectories (can be a folder or a file). If it's a folder, the trajectories will be saved in a file named with the session id name and .json extension, in that folder.
```

2024-11-25 12:20 UTC, enyst commented on docs/modules/usage/configuration-options.md
> +  - Default: `"your-api-key"`
```suggestion
  - Default: `None`
```

2024-11-25 12:23 UTC, enyst commented on docs/modules/usage/configuration-options.md
> +  - Default: `10000`
```suggestion
  - Default: `30000`
```

2024-11-25 12:23 UTC, enyst commented on docs/modules/usage/configuration-options.md
> +  - Description: Maximum number of characters in an observation's content
```suggestion
  - Description: The approximate maximum number of characters in the content of an event included in the prompt to the LLM. Larger observations are truncated.
```

2024-11-25 12:30 UTC, enyst commented on docs/modules/usage/configuration-options.md
> +  - Default: `true`
```suggestion
  - Default: `None`
```

2024-11-25 12:42 UTC, enyst commented
@Mr-Imperium This looks good! Only had very minor tweaks to suggest, please take a quick look if you can.

Happy to approve this PR if that's fine with you. This is a good start to document all these, thank you for doing this!

2024-11-26 15:06 UTC, Mr-Imperium commented
> @Mr-Imperium This looks good! Only had very minor tweaks to suggest, please take a quick look if you can.
> 
> Happy to approve this PR if that's fine with you. This is a good start to document all these, thank you for doing this!

Happy to have been able to contribute! Just a beginner; your guidance has been invaluable. Thanks!

2024-11-26 15:17 UTC, enyst commented on docs/modules/usage/configuration-options.md
> +This guide details all configuration options available for OpenHands, helping you customize its behavior and integrate it with other services. Required options and those with recommended settings are
```suggestion
This guide details all configuration options available for OpenHands, helping you customize its behavior and integrate it with other services.
```

2024-11-26 15:18 UTC, enyst approved these changes

2024-11-26 15:52 UTC, enyst commented
@mamoodi I think the contents here are great to have and this kind of doc is needed for a long time, so I'd like to take this in.

2024-11-26 15:52 UTC, merged