Show the link to the All Hands product roadmap
All-Hands-AI/OpenHands pull request #5192
Opened 2024-11-21 22:35 UTC by ryx2

**End-user friendly description of the problem this fixes or functionality that this introduces**

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

Shows people the all hands public roadmap, so open source contributors can hopefully tailor their changes to align with the openhands maintainers. 

---
**Link of any specific issues this addresses**

2024-11-21 22:36 UTC, ryx2 commented
https://github.com/All-Hands-AI/OpenHands/issues/5191

2024-11-21 22:36 UTC, ryx2 commented
https://github.com/All-Hands-AI/OpenHands/issues/5191

2024-11-22 14:07 UTC, neubig requested changes
Let's change "All Hands product roadmap"  to "Openhands roadmap", and move it to the top of the "progress" section.

2024-11-22 15:51 UTC, rbren approved these changes

2024-11-22 16:18 UTC, neubig commented on README.md
>  ## 📈 Progress
```suggestion
## 📈 Progress

See the monthly OpenHands roadmap [here](https://github.com/orgs/All-Hands-AI/projects/1) (updated at the maintainer's meeting at the end of each month).
```

2024-11-22 16:18 UTC, neubig approved these changes
Fixed so this should be ready to merge!

2024-11-22 16:43 UTC, merged

2024-11-22 19:03 UTC, ryx2 commented
Any thoughts on also putting this in the "contributing" md?