feat: Integrate Langfuse
All-Hands-AI/OpenHands pull request #5580
Opened 2024-12-13 13:37 UTC by motin

**End-user friendly description of the problem this fixes or functionality that this introduces**

- [x] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

Langfuse integration

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

Integrates Langfuse as per docs at https://litellm.vercel.app/docs/observability/langfuse_integration. If openhands is started with the required LANGFUSE_ env vars, LLM traces is sent to the configured Langfuse server. If the env vars are not set, the callbacks are no-ops.

The rationale is to more easily be able to track costs and get insights into the queries that are being sent to the LLM during openhands operation.

---
**Link of any specific issues this addresses**

2024-12-14 06:07 UTC, diwu-sf commented
This doesn't feel like the kind of thing that should be included by default.

2024-12-14 20:41 UTC, neubig requested changes
Hey @motin , I tend to agree with @diwu-sf . I think that this might be a good feature to have for some users, but we're trying to avoid dependency bloat in the main project, so if you want this could you make it optional and remove it from the main section of `pyproject.toml`?

2024-12-16 07:38 UTC, motin commented
@openhands-agent we're trying to avoid dependency bloat in the main project, so could you make the langfuse dependency optional and remove it from the main section of pyproject.toml?

2024-12-16 07:48 UTC, enyst commented
I'm sorry, it won't want to work on forks, only on the repo's own branches. So you could try it on your repo if you want, then push the result here?

2024-12-30 15:30 UTC, mamoodi commented
@motin is this still a work in progress?

2025-01-06 16:56 UTC, mamoodi commented
Going to close this for now. Please feel free to reopen a new PR when ready or we can reopen this one if it was mistakenly closed.

2025-01-06 16:56 UTC, closed without merging

2025-01-20 14:17 UTC, motin commented
Thanks, yes this can remain closed since I found that using a LLM router like https://agentrouter.dev made it very simple to transparently add langfuse tracing to all openhands requests.

2025-01-20 15:50 UTC, marcklingen commented
@motin I'm one of the langfuse maintainers, can you point me to the agentrouter docs that explain how the integration works? many teams use langfuse in conjunction with litellm if they want to use a router to log to langfuse

2025-02-05 11:50 UTC, motin commented
@marcklingen sure it's explained on https://github.com/augmentedmind/agentrouter