Feat search conversations
All-Hands-AI/OpenHands pull request #5775
Opened 2024-12-23 21:36 UTC by tofarr

NOT READY FOR REVIEW YET!
**End-user friendly description of the problem this fixes or functionality that this introduces**

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**

---
**Link of any specific issues this addresses**

2025-01-01 22:43 UTC, enyst commented on openhands/storage/conversation/conversation_store.py
> +    ConversationMetadataResultSet,
Can we move the `data_models` in `storage`, or elsewhere, out of the `server`? I think `storage` shouldn't depend on `server`, it makes more sense the other way around.

2025-01-02 13:24 UTC, amanape approved these changes
LGTM

2025-01-02 13:24 UTC, amanape commented on openhands/server/data_models/conversation_status.py
> +    STOPPED = 'STOPPED'
Are these WS states?

2025-01-02 13:39 UTC, amanape commented on openhands/server/data_models/conversation_info.py
> +    title: str | None = None
I think we are always going to have a title, with a default name probably being a substring of the conversation ID (e.g., `Conversation abc-123`)

2025-01-02 13:39 UTC, amanape commented on openhands/server/data_models/conversation_info.py
> +    last_updated_at: datetime | None = None
Wouldn't this default to now?

2025-01-02 13:44 UTC, amanape commented on openhands/server/routes/new_conversation.py
> +        return None
Would be cleaner if you moved this to either:
- Top of file
- Utils file

2025-01-02 13:51 UTC, amanape commented on openhands/storage/conversation/file_conversation_store.py
> +            for path in self.file_store.list(metadata_dir)
What if it doesn't exist?

`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/file_store/sessions'`

2025-01-02 13:58 UTC, amanape commented on openhands/server/routes/new_conversation.py
>      return JSONResponse(content={'status': 'ok', 'conversation_id': conversation_id})
Maybe we can return the actual conversation object here or we'll have inconsistent return types (other endpoints return `conversation.id` while this one returns `conversation.conversation_id`)

2025-01-02 14:06 UTC, amanape commented
Also, were you planning on adding a PUT endpoint in this PR (e.g., changing the title)?

2025-01-02 14:15 UTC, tofarr commented
> Also, were you planning on adding a PUT endpoint in this PR (e.g., changing the title)?

I had inccorrectly used `post` for this on line 130 - you are correct that it is an updated and should be `put`.

2025-01-02 14:58 UTC, rbren commented on openhands/utils/conversation_utils.py
> +        event_path = events[-1]
I think the pickled conversation State has a latest_event_id or similar. Maybe we should just pickle last_update_time

2025-01-02 15:07 UTC, enyst commented on openhands/utils/conversation_utils.py
> +        event_path = events[-1]
State pickles a `start_id` and an `end_id`, although `end_id` is not currently used.

The eventstream has a `get_latest_event_id()`.

What is the intended relationship between an event stream (which is 1:1 with sid) and conversations?

2025-01-02 18:09 UTC, enyst commented on openhands/utils/conversation_utils.py
> +        file_store = session_manager.file_store
Could we avoid using `session_manager` here? Like, maybe we can have `file_store` as parameter, if we cannot read it from config.

The reason is similar: the `server` functionalities depend on the backend normally, while this would add a reversed dependency.

2025-01-02 18:45 UTC, rbren commented on openhands/server/middleware.py
> +            if len(path_parts) > 4:
why did this change? /api/conversations/foo should have 4 parts

2025-01-02 18:47 UTC, rbren commented on openhands/utils/conversation_utils.py
> +            title = f'Conversation {conversation.conversation_id}'
Maybe `conversation.conversation_id[:5]` as a shortname?

2025-01-02 18:49 UTC, rbren commented on openhands/utils/conversation_utils.py
> +from datetime import datetime
this utils folder is getting out of hand 😓 probably another thing to refactor in the future

2025-01-02 18:49 UTC, rbren approved these changes
Looking great!

2025-01-02 19:25 UTC, enyst requested changes
This is a nice feature! I just have a doubt, a simple thing about architecture here:
the event stream and its management is self-contained -ish, enough that it has always been possible, I think, to load in cli the event streams created with an UI.

Give or take that they have ugly names, 😅 but otherwise, there are no major reasons not to work. They're just events.

With the caveat that I haven't looked much in the past couple of weeks, this appears to be the case after the introduction of conversations too. At least I _think_ it works with the default convo.

Is there a reason why managing it from cli wouldn't continue to work, with sessions or with convos alike?
In this PR the server code is not really minimally separated from backend.

Can we keep it _possible_ to add in cli? It doesn't have to be _implemented_ in this PR, of course, but I do think it would be nice to not go against it either: for example, the inverse dependencies mean that one cannot use the methods in `utils`, even though they're in `utils`.

All we'd need here, is to keep separate the code that works with the stream and file store, from code that works with the `session_manager` global or `sio` etc. What do you think?

2025-01-02 19:32 UTC, enyst commented on openhands/utils/conversation_utils.py
> +from openhands.server.shared import config
Can we have the functions that import from `server` in a `server` module, like its `shared.py`? IMHO the new callback is only useful for `server`, right?

2025-01-02 19:36 UTC, tofarr commented
@enyst - At the moment, this PR leverages the existing functionality where conversation metadata is stored when a conversation is started in web . I just did a quick check, and the same metadata is not being stored for conversations started in CLI mode - I think we should create a second PR to remedy this issue
![image](https://github.com/user-attachments/assets/ac982307-de6a-43f0-b098-6672d06ee0e5)

2025-01-02 19:42 UTC, enyst commented
That's okay, we don't need to create metadata, sure. I just feel like this PR is heading in the opposite direction, when it adds more dependencies to `server` in the backend. That means we'd first need to untangle them, and then be able to access the file store / data / metadata.

Could we just move the new callback function, for example, if it depends on `server`, to the `server` somewhere? It feels like the work with the stream/convo in the backend shouldn't depend on it?

2025-01-02 20:06 UTC, enyst approved these changes

2025-01-02 20:11 UTC, enyst commented
Ah, too bad it comes at the price of not exposing the `get info` function. It didn't seem to depend on `session_manager` anymore, so maybe we can actually reuse it sometime. It doesn't have to be in this PR though. Thank you, this feature will be super useful!

2025-01-02 23:09 UTC, merged