feat(frontend): Add active status for ws
All-Hands-AI/OpenHands pull request #5944
Opened 2024-12-31 17:59 UTC by amanape

**End-user friendly description of the problem this fixes or functionality that this introduces**
- Endpoints such as `/list-files` should only call once runtime is active
- We have two status' `CONNECTED` and `DISCONNECTED`. WS is set to `CONNECTED` if a ws connection is established, not when runtime is active

- [ ] Include this change in the Release Notes. If checked, you must provide an **end-user friendly** description for your change below

---
**Give a summary of what the PR does, explaining any non-trivial design decisions**
- Create a new `ACTIVE` status

---
**Link of any specific issues this addresses**

2024-12-31 18:23 UTC, rbren requested changes
This is the wrong fix. will follow up

2024-12-31 18:23 UTC, rbren commented
@amanape we should check AgentStatus rather than adding agent state into the websocket state

2025-01-02 22:38 UTC, rbren commented on frontend/src/routes/_oh.app/hooks/use-ws-status-change.ts
> +    if (status !== WsClientProviderStatus.DISCONNECTED && initialQuery) {
any particular reason for these flips? Or just a remnant of the original implementation?

2025-01-02 22:38 UTC, rbren approved these changes

2025-01-03 12:37 UTC, amanape commented on frontend/src/routes/_oh.app/hooks/use-ws-status-change.ts
> +    if (status !== WsClientProviderStatus.DISCONNECTED && initialQuery) {
They are remnants of the original implementation, but are also helpful in the (unlikely) case we extend the `WsClientProviderStatus` enum

2025-01-03 12:38 UTC, amanape commented on frontend/src/routes/_oh.app/hooks/use-ws-status-change.ts
> +    if (status !== WsClientProviderStatus.DISCONNECTED && initialQuery) {
LMK if you think we should change it, should be a minute-PR

2025-01-03 12:38 UTC, merged